// Generated by CoffeeScript 1.7.1
(function() {
  var API, APIRouteModel, AbstractCollection, AbstractData, AbstractModal, AbstractModel, AbstractView, AbstractViewModal, AbstractViewPage, Analytics, App, AppData, AppView, AuthManager, DateUtils, ExamplePageView, Facebook, Footer, GooglePlus, Header, HomeView, IS_LIVE, ImageLoader, Locale, LocalesModel, ModalManager, Nav, NumberUtils, OrientationModal, PostParser, Preloader, Requester, Router, Share, TemplateModel, Templates, TemplatesCollection, UserData, UserInfoModel, UserStatusModel, Wrapper, view,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  AbstractModel = (function(_super) {
    __extends(AbstractModel, _super);

    function AbstractModel() {
      this.__NAMESPACE__ = __bind(this.__NAMESPACE__, this);
      return AbstractModel.__super__.constructor.apply(this, arguments);
    }

    AbstractModel.prototype.__NAMESPACE__ = function() {
      return view.__NAMESPACE__;
    };

    return AbstractModel;

  })(Backbone.DeepModel);

  APIRouteModel = (function(_super) {
    __extends(APIRouteModel, _super);

    function APIRouteModel() {
      return APIRouteModel.__super__.constructor.apply(this, arguments);
    }

    APIRouteModel.prototype.defaults = {
      start: "{{ BASE_PATH }}/api/start",
      locale: "{{ BASE_PATH }}/api/l10n/{{ code }}",
      user: {
        login: "{{ BASE_PATH }}/api/user/login",
        register: "{{ BASE_PATH }}/api/user/register",
        password: "{{ BASE_PATH }}/api/user/password",
        update: "{{ BASE_PATH }}/api/user/update",
        logout: "{{ BASE_PATH }}/api/user/logout",
        remove: "{{ BASE_PATH }}/api/user/remove"
      }
    };

    return APIRouteModel;

  })(Backbone.DeepModel);

  LocalesModel = (function(_super) {
    __extends(LocalesModel, _super);

    function LocalesModel() {
      this.getString = __bind(this.getString, this);
      this.get_language = __bind(this.get_language, this);
      return LocalesModel.__super__.constructor.apply(this, arguments);
    }

    LocalesModel.prototype.defaults = {
      code: null,
      language: null,
      strings: null
    };

    LocalesModel.prototype.get_language = function() {
      return this.get('language');
    };

    LocalesModel.prototype.getString = function(id) {
      var a, e, k, v, _ref, _ref1;
      _ref = this.get('strings');
      for (k in _ref) {
        v = _ref[k];
        _ref1 = v['strings'];
        for (a in _ref1) {
          e = _ref1[a];
          if (a === id) {
            return e;
          }
        }
      }
      console.warn("Locales -> not found string: " + id);
      return null;
    };

    return LocalesModel;

  })(Backbone.Model);

  TemplateModel = (function(_super) {
    __extends(TemplateModel, _super);

    function TemplateModel() {
      return TemplateModel.__super__.constructor.apply(this, arguments);
    }

    TemplateModel.prototype.defaults = {
      id: "",
      text: ""
    };

    return TemplateModel;

  })(Backbone.Model);

  UserInfoModel = (function(_super) {
    __extends(UserInfoModel, _super);

    function UserInfoModel() {
      return UserInfoModel.__super__.constructor.apply(this, arguments);
    }

    UserInfoModel.prototype.defaults = "";

    return UserInfoModel;

  })(AbstractModel);

  UserStatusModel = (function(_super) {
    __extends(UserStatusModel, _super);

    function UserStatusModel() {
      return UserStatusModel.__super__.constructor.apply(this, arguments);
    }

    UserStatusModel.prototype.defaults = {
      logged: false
    };

    return UserStatusModel;

  })(AbstractModel);

  AbstractCollection = (function(_super) {
    __extends(AbstractCollection, _super);

    function AbstractCollection() {
      this.__NAMESPACE__ = __bind(this.__NAMESPACE__, this);
      return AbstractCollection.__super__.constructor.apply(this, arguments);
    }

    AbstractCollection.prototype.__NAMESPACE__ = function() {
      return view.__NAMESPACE__;
    };

    return AbstractCollection;

  })(Backbone.Collection);

  TemplatesCollection = (function(_super) {
    __extends(TemplatesCollection, _super);

    function TemplatesCollection() {
      return TemplatesCollection.__super__.constructor.apply(this, arguments);
    }

    TemplatesCollection.prototype.model = TemplateModel;

    return TemplatesCollection;

  })(Backbone.Collection);

  AbstractData = (function() {
    function AbstractData() {
      this.__NAMESPACE__ = __bind(this.__NAMESPACE__, this);
      _.extend(this, Backbone.Events);
      return null;
    }

    AbstractData.prototype.__NAMESPACE__ = function() {
      return view.__NAMESPACE__;
    };

    return AbstractData;

  })();

  API = (function() {
    function API() {}

    API.model = new APIRouteModel;

    API.getContants = function() {
      return {

        /* add more if we wanna use in API strings */
        BASE_PATH: API.__NAMESPACE__().BASE_PATH
      };
    };

    API.get = function(name, vars) {
      vars = $.extend(true, vars, API.getContants());
      return API.supplantString(API.model.get(name), vars);
    };

    API.supplantString = function(str, vals) {
      return str.replace(/{{ ([^{}]*) }}/g, function(a, b) {
        var r;
        return r = vals[b] || (typeof vals[b] === 'number' ? vals[b].toString() : '');
      });
      if (typeof r === "string" || typeof r === "number") {
        return r;
      } else {
        return a;
      }
    };

    API.__NAMESPACE__ = function() {
      return view.__NAMESPACE__;
    };

    return API;

  })();


  /*
   * Locale Loader #
  
  Fires back an event when complete
   */

  Locale = (function() {
    Locale.prototype.lang = null;

    Locale.prototype.data = null;

    Locale.prototype.callback = null;

    Locale.prototype.backup = null;

    Locale.prototype["default"] = 'en-gb';

    function Locale(data, cb) {
      this.getLocaleImage = __bind(this.getLocaleImage, this);
      this.get = __bind(this.get, this);
      this.loadBackup = __bind(this.loadBackup, this);
      this.onSuccess = __bind(this.onSuccess, this);
      this.getLang = __bind(this.getLang, this);

      /* start Locale Loader, define locale based on browser language */
      this.callback = cb;
      this.backup = data;
      this.lang = this.getLang();
      $.ajax({
        url: API.get('locale', {
          code: this.lang
        }),
        type: 'GET',
        success: this.onSuccess,
        error: this.loadBackup
      });
      null;
    }

    Locale.prototype.getLang = function() {
      var lang;
      if (window.location.search && window.location.search.match('lang=')) {
        lang = window.location.search.split('lang=')[1].split('&')[0];
      } else if (window.config.localeCode) {
        lang = window.config.localeCode;
      } else {
        lang = this["default"];
      }
      return lang;
    };

    Locale.prototype.onSuccess = function(event) {

      /* Fires back an event once it's complete */
      var d;
      d = null;
      if (event.responseText) {
        d = JSON.parse(event.responseText);
      } else {
        d = event;
      }
      this.data = new LocalesModel(d);
      if (typeof this.callback === "function") {
        this.callback();
      }
      return null;
    };

    Locale.prototype.loadBackup = function() {

      /* When API not available, tries to load the static .txt locale */
      $.ajax({
        url: this.backup,
        dataType: 'json',
        complete: this.onSuccess,
        error: (function(_this) {
          return function() {
            return console.log('error on loading backup');
          };
        })(this)
      });
      return null;
    };

    Locale.prototype.get = function(id) {

      /* get String from locale
      + id : string id of the Localised String
       */
      return this.data.getString(id);
    };

    Locale.prototype.getLocaleImage = function(url) {
      return window.config.CDN + "/images/locale/" + window.config.localeCode + "/" + url;
    };

    return Locale;

  })();

  Templates = (function() {
    Templates.prototype.templates = null;

    Templates.prototype.cb = null;

    function Templates(templates, callback) {
      this.get = __bind(this.get, this);
      this.parseXML = __bind(this.parseXML, this);
      this.cb = callback;
      $.ajax({
        url: templates,
        success: this.parseXML
      });
      null;
    }

    Templates.prototype.parseXML = function(data) {
      var temp;
      temp = [];
      $(data).find('template').each(function(key, value) {
        var $value;
        $value = $(value);
        return temp.push(new TemplateModel({
          id: $value.attr('id').toString(),
          text: $.trim($value.text())
        }));
      });
      this.templates = new TemplatesCollection(temp);
      if (typeof this.cb === "function") {
        this.cb();
      }
      return null;
    };

    Templates.prototype.get = function(id) {
      var t;
      t = this.templates.where({
        id: id
      });
      t = t[0].get('text');
      return $.trim(t);
    };

    return Templates;

  })();

  UserData = (function(_super) {
    __extends(UserData, _super);

    UserData.prototype.status = null;

    UserData.prototype.info = null;

    UserData.prototype.EVENT_USER_LOGGED = 'EVENT_USER_LOGGED';

    function UserData() {
      this.onLogoutDone = __bind(this.onLogoutDone, this);
      this.removeUser = __bind(this.removeUser, this);
      this.logout = __bind(this.logout, this);
      this.loginFail = __bind(this.loginFail, this);
      this.loginSuccess = __bind(this.loginSuccess, this);
      this.login = __bind(this.login, this);
      this.registerFail = __bind(this.registerFail, this);
      this.registerSuccess = __bind(this.registerSuccess, this);
      this.register = __bind(this.register, this);
      this.onLoggedChange = __bind(this.onLoggedChange, this);
      this.bindEvents = __bind(this.bindEvents, this);
      this.status = new UserStatusModel;
      this.info = new UserInfoModel;
      UserData.__super__.constructor.call(this);
      this.bindEvents();
      return null;
    }

    UserData.prototype.bindEvents = function() {
      this.status.on('change:logged', this.onLoggedChange);
      return null;
    };

    UserData.prototype.onLoggedChange = function() {
      if (this.status.get('logged')) {
        this.trigger(this.EVENT_USER_LOGGED);
      }
      return null;
    };

    UserData.prototype.register = function(data) {
      var r;
      r = Requester.request({
        url: API.get('user.register'),
        type: "POST",
        data: data
      });
      r.done(this.registerSuccess);
      r.fail(this.registerFail);
      return r;
    };

    UserData.prototype.registerSuccess = function(res) {
      console.log("register successful -->", res);
      return res;
      return null;
    };

    UserData.prototype.registerFail = function(res) {
      console.log("register fail -->", res);
      return res;
      return null;
    };

    UserData.prototype.login = function(data) {
      var r;
      r = Requester.request({
        url: API.get('user.login'),
        type: "POST",
        data: data
      });
      r.done(this.loginSuccess);
      r.fail(this.loginFail);
      return r;
    };

    UserData.prototype.loginSuccess = function(res) {
      console.log("login successful -->", res);
      if (!res.user) {
        return;
      }
      return null;
    };

    UserData.prototype.loginFail = function(res) {
      console.log("failed to log in... -->", res);
      return null;
    };

    UserData.prototype.logout = function(removeUser) {
      var endpoint, r;
      if (removeUser == null) {
        removeUser = false;
      }
      endpoint = removeUser ? API.get('user.remove') : API.get('user.logout');
      r = Requester.request({
        url: endpoint,
        type: "POST"
      });
      r.done(this.onLogoutDone);
      return null;
    };

    UserData.prototype.removeUser = function() {
      this.logout(true);
      return null;
    };

    UserData.prototype.onLogoutDone = function() {
      window.location.href = this.__NAMESPACE__().BASE_PATH;
      return null;
    };

    return UserData;

  })(AbstractData);

  AppData = (function(_super) {
    __extends(AppData, _super);

    AppData.prototype.callback = null;

    function AppData(callback) {
      this.callback = callback;
      this.onStartDataReceived = __bind(this.onStartDataReceived, this);
      this.getStartData = __bind(this.getStartData, this);

      /*
      
      		add all data classes here
       */
      AppData.__super__.constructor.call(this);
      this.getStartData();
      return null;
    }


    /*
    	get app bootstrap data - embed in HTML or API endpoint
     */

    AppData.prototype.getStartData = function() {
      var r;
      r = Requester.request({
        url: API.get('start'),
        type: 'GET'
      });
      r.done(this.onStartDataReceived);
      r.fail((function(_this) {
        return function() {

          /*
          			this is only temporary, while there is no bootstrap data here, normally would handle error / fail
           */
          return typeof _this.callback === "function" ? _this.callback() : void 0;
        };
      })(this));
      return null;
    };

    AppData.prototype.onStartDataReceived = function(data) {

      /*
      
      		bootstrap data received, app ready to go
       */
      if (typeof this.callback === "function") {
        this.callback();
      }
      return null;
    };

    return AppData;

  })(AbstractData);


  /*
  Analytics wrapper
   */

  Analytics = (function() {
    Analytics.prototype.tags = null;

    Analytics.prototype.started = false;

    Analytics.prototype.attempts = 0;

    Analytics.prototype.allowedAttempts = 5;

    function Analytics(tags, callback) {
      this.callback = callback;
      this.track = __bind(this.track, this);
      this.onTagsReceived = __bind(this.onTagsReceived, this);
      $.getJSON(tags, this.onTagsReceived);
      return null;
    }

    Analytics.prototype.onTagsReceived = function(data) {
      this.tags = data;
      this.started = true;
      if (typeof this.callback === "function") {
        this.callback();
      }
      return null;
    };


    /*
    @param string id of the tracking tag to be pushed on Analytics
     */

    Analytics.prototype.track = function(param) {
      var arg, args, v, _i, _len;
      if (!this.started) {
        return;
      }
      if (param) {
        v = this.tags[param];
        if (v) {
          args = ['send', 'event'];
          for (_i = 0, _len = v.length; _i < _len; _i++) {
            arg = v[_i];
            args.push(arg);
          }
          if (window.ga) {
            ga.apply(null, args);
          } else if (this.attempts >= this.allowedAttempts) {
            this.started = false;
          } else {
            setTimeout((function(_this) {
              return function() {
                _this.track(param);
                return _this.attempts++;
              };
            })(this), 2000);
          }
        }
      }
      return null;
    };

    return Analytics;

  })();

  AuthManager = (function(_super) {
    __extends(AuthManager, _super);

    AuthManager.prototype.userData = null;

    AuthManager.prototype.process = false;

    AuthManager.prototype.processTimer = null;

    AuthManager.prototype.processWait = 5000;

    function AuthManager() {
      this.hideLoader = __bind(this.hideLoader, this);
      this.showLoader = __bind(this.showLoader, this);
      this.authCallback = __bind(this.authCallback, this);
      this.authFail = __bind(this.authFail, this);
      this.authSuccess = __bind(this.authSuccess, this);
      this.login = __bind(this.login, this);
      this.userData = this.__NAMESPACE__().appData.USER;
      AuthManager.__super__.constructor.call(this);
      return null;
    }

    AuthManager.prototype.login = function(service, cb) {
      var $dataDfd;
      if (cb == null) {
        cb = null;
      }
      if (this.process) {
        return;
      }
      this.showLoader();
      this.process = true;
      $dataDfd = $.Deferred();
      switch (service) {
        case 'google':
          GooglePlus.login($dataDfd);
          break;
        case 'facebook':
          Facebook.login($dataDfd);
      }
      $dataDfd.done((function(_this) {
        return function(res) {
          return _this.authSuccess(service, res);
        };
      })(this));
      $dataDfd.fail((function(_this) {
        return function(res) {
          return _this.authFail(service, res);
        };
      })(this));
      $dataDfd.always((function(_this) {
        return function() {
          return _this.authCallback(cb);
        };
      })(this));

      /*
      		Unfortunately no callback is fired if user manually closes G+ login modal,
      		so this is to allow them to close window and then subsequently try to log in again...
       */
      this.processTimer = setTimeout(this.authCallback, this.processWait);
      return $dataDfd;
    };

    AuthManager.prototype.authSuccess = function(service, data) {
      return null;
    };

    AuthManager.prototype.authFail = function(service, data) {
      return null;
    };

    AuthManager.prototype.authCallback = function(cb) {
      if (cb == null) {
        cb = null;
      }
      if (!this.process) {
        return;
      }
      clearTimeout(this.processTimer);
      this.hideLoader();
      this.process = false;
      if (typeof cb === "function") {
        cb();
      }
      return null;
    };


    /*
    	show / hide some UI indicator that we are waiting for social network to respond
     */

    AuthManager.prototype.showLoader = function() {
      return null;
    };

    AuthManager.prototype.hideLoader = function() {
      return null;
    };

    return AuthManager;

  })(AbstractData);

  DateUtils = (function() {
    function DateUtils() {}

    DateUtils.getLocalDate = function(dateString, timeString, dayCorrection) {
      var d, splited, timestamp;
      if (dayCorrection == null) {
        dayCorrection = 0;
      }
      splited = dateString.split('/');
      dateString = [splited[1], splited[0], "20" + splited[2]].join('/');
      d = new Date("" + dateString + " " + timeString + " UTC");
      timestamp = d.getTime() + 10800000 + dayCorrection * 86400000;
      return new Date(timestamp);
    };

    return DateUtils;

  })();


  /*
  
  Facebook SDK wrapper - load asynchronously, some helper methods
   */

  Facebook = (function(_super) {
    __extends(Facebook, _super);

    function Facebook() {
      return Facebook.__super__.constructor.apply(this, arguments);
    }

    Facebook.url = '//connect.facebook.net/en_US/all.js';

    Facebook.permissions = 'email';

    Facebook.$dataDfd = null;

    Facebook.loaded = false;

    Facebook.load = function() {
      require([Facebook.url], Facebook.init);
      return null;
    };

    Facebook.init = function() {
      Facebook.loaded = true;
      FB.init({
        appId: window.config.fb_app_id,
        status: false,
        xfbml: false
      });
      return null;
    };

    Facebook.login = function($dataDfd) {
      Facebook.$dataDfd = $dataDfd;
      if (!Facebook.loaded) {
        return Facebook.$dataDfd.reject('SDK not loaded');
      }
      FB.login(function(res) {
        if (res['status'] === 'connected') {
          return Facebook.getUserData(res['authResponse']['accessToken']);
        } else {
          return Facebook.$dataDfd.reject('no way jose');
        }
      }, {
        scope: Facebook.permissions
      });
      return null;
    };

    Facebook.getUserData = function(token) {
      var $meDfd, $picDfd, userData;
      userData = {};
      userData.access_token = token;
      $meDfd = $.Deferred();
      $picDfd = $.Deferred();
      FB.api('/me', function(res) {
        userData.full_name = res.name;
        userData.social_id = res.id;
        userData.email = res.email || false;
        return $meDfd.resolve();
      });
      FB.api('/me/picture', {
        'width': '200'
      }, function(res) {
        userData.profile_pic = res.data.url;
        return $picDfd.resolve();
      });
      $.when($meDfd, $picDfd).done(function() {
        return Facebook.$dataDfd.resolve(userData);
      });
      return null;
    };

    Facebook.share = function(opts, cb) {
      FB.ui({
        method: opts.method || 'feed',
        name: opts.name || '',
        link: opts.link || '',
        picture: opts.picture || '',
        caption: opts.caption || '',
        description: opts.description || ''
      }, function(response) {
        return typeof cb === "function" ? cb(response) : void 0;
      });
      return null;
    };

    return Facebook;

  })(AbstractData);


  /*
  
  Google+ SDK wrapper - load asynchronously, some helper methods
   */

  GooglePlus = (function(_super) {
    __extends(GooglePlus, _super);

    function GooglePlus() {
      return GooglePlus.__super__.constructor.apply(this, arguments);
    }

    GooglePlus.url = 'https://apis.google.com/js/client:plusone.js';

    GooglePlus.params = {
      'clientid': null,
      'callback': null,
      'scope': 'https://www.googleapis.com/auth/userinfo.email',
      'cookiepolicy': 'none'
    };

    GooglePlus.$dataDfd = null;

    GooglePlus.loaded = false;

    GooglePlus.load = function() {
      require([GooglePlus.url], GooglePlus.init);
      return null;
    };

    GooglePlus.init = function() {
      GooglePlus.loaded = true;
      GooglePlus.params['clientid'] = window.config.gp_app_id;
      GooglePlus.params['callback'] = GooglePlus.loginCallback;
      return null;
    };

    GooglePlus.login = function($dataDfd) {
      GooglePlus.$dataDfd = $dataDfd;
      if (GooglePlus.loaded) {
        gapi.auth.signIn(GooglePlus.params);
      } else {
        GooglePlus.$dataDfd.reject('SDK not loaded');
      }
      return null;
    };

    GooglePlus.loginCallback = function(res) {
      if (res['status']['signed_in']) {
        GooglePlus.getUserData(res['access_token']);
      } else if (res['error']['access_denied']) {
        GooglePlus.$dataDfd.reject('no way jose');
      }
      return null;
    };

    GooglePlus.getUserData = function(token) {
      gapi.client.load('plus', 'v1', function() {
        var request;
        request = gapi.client.plus.people.get({
          'userId': 'me'
        });
        return request.execute(function(res) {
          var userData;
          userData = {
            access_token: token,
            full_name: res.displayName,
            social_id: res.id,
            email: res.emails[0] ? res.emails[0].value : false,
            profile_pic: res.image.url
          };
          return GooglePlus.$dataDfd.resolve(userData);
        });
      });
      return null;
    };

    return GooglePlus;

  })(AbstractData);

  ImageLoader = (function() {
    function ImageLoader() {}

    ImageLoader.load = function(src) {
      var dfd, img;
      dfd = $.Deferred();
      img = new Image();
      img.onload = (function(_this) {
        return function() {
          return dfd.resolve(img);
        };
      })(this);
      img.src = src;
      return dfd;
    };

    ImageLoader.loadSet = function(set) {
      var i, loaders, _i, _len;
      loaders = [];
      for (_i = 0, _len = set.length; _i < _len; _i++) {
        i = set[_i];
        loaders.push(ImageLoader.load(i).promise());
      }
      return $.when.apply(null, loaders);
    };

    return ImageLoader;

  })();

  NumberUtils = (function() {
    function NumberUtils() {}

    NumberUtils.MATH_COS = Math.cos;

    NumberUtils.MATH_SIN = Math.sin;

    NumberUtils.MATH_RANDOM = Math.random;

    NumberUtils.MATH_ABS = Math.abs;

    NumberUtils.MATH_ATAN2 = Math.atan2;

    NumberUtils.limit = function(number, min, max) {
      return Math.min(Math.max(min, number), max);
    };

    NumberUtils.map = function(num, min1, max1, min2, max2, round, constrainMin, constrainMax) {
      var num1, num2;
      if (round == null) {
        round = false;
      }
      if (constrainMin == null) {
        constrainMin = true;
      }
      if (constrainMax == null) {
        constrainMax = true;
      }
      if (constrainMin && num < min1) {
        return min2;
      }
      if (constrainMax && num > max1) {
        return max2;
      }
      num1 = (num - min1) / (max1 - min1);
      num2 = (num1 * (max2 - min2)) + min2;
      if (round) {
        return Math.round(num2);
      }
      return num2;
    };

    NumberUtils.getRandomColor = function() {
      var color, i, letters, _i;
      letters = '0123456789ABCDEF'.split('');
      color = '#';
      for (i = _i = 0; _i < 6; i = ++_i) {
        color += letters[Math.round(Math.random() * 15)];
      }
      return color;
    };

    NumberUtils.getTimeStampDiff = function(date1, date2) {
      var date1_ms, date2_ms, difference_ms, one_day, time;
      one_day = 1000 * 60 * 60 * 24;
      time = {};
      date1_ms = date1.getTime();
      date2_ms = date2.getTime();
      difference_ms = date2_ms - date1_ms;
      difference_ms = difference_ms / 1000;
      time.seconds = Math.floor(difference_ms % 60);
      difference_ms = difference_ms / 60;
      time.minutes = Math.floor(difference_ms % 60);
      difference_ms = difference_ms / 60;
      time.hours = Math.floor(difference_ms % 24);
      time.days = Math.floor(difference_ms / 24);
      return time;
    };

    NumberUtils.map = function(num, min1, max1, min2, max2, round, constrainMin, constrainMax) {
      var num1, num2;
      if (round == null) {
        round = false;
      }
      if (constrainMin == null) {
        constrainMin = true;
      }
      if (constrainMax == null) {
        constrainMax = true;
      }
      if (constrainMin && num < min1) {
        return min2;
      }
      if (constrainMax && num > max1) {
        return max2;
      }
      num1 = (num - min1) / (max1 - min1);
      num2 = (num1 * (max2 - min2)) + min2;
      if (round) {
        return Math.round(num2);
      }
      return num2;
    };

    NumberUtils.toRadians = function(degree) {
      return degree * (Math.PI / 180);
    };

    NumberUtils.toDegree = function(radians) {
      return radians * (180 / Math.PI);
    };

    NumberUtils.isInRange = function(num, min, max, canBeEqual) {
      if (canBeEqual) {
        return num >= min && num <= max;
      } else {
        return num >= min && num <= max;
      }
    };

    NumberUtils.getNiceDistance = function(metres) {
      var km;
      if (metres < 1000) {
        return "" + (Math.round(metres)) + "M";
      } else {
        km = (metres / 1000).toFixed(2);
        return "" + km + "KM";
      }
    };

    return NumberUtils;

  })();

  PostParser = (function() {
    function PostParser() {}

    PostParser.getRichText = function(post) {
      var richText, type;
      type = PostParser._getPostType(post);
      return richText = (function() {
        switch (true) {
          case type === 'twitter':
            return PostParser._getRichText_TW(post.text);
          case type === 'instagram':
            return PostParser._getRichText_IG(post.text);
        }
      })();
    };

    PostParser._getRichText_TW = function(text) {
      var exp;
      exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
      text = text.replace(exp, "<a href='$1' target='_blank'>$1</a>");
      exp = /#(\w+)/g;
      text = text.replace(exp, "<a href='http://twitter.com/search?q=%23$1' target='_blank'>#$1</a>");
      exp = /@(\w+)/g;
      text = text.replace(exp, "<a href='http://www.twitter.com/$1' target='_blank'>@$1</a>");
      return text;
    };

    PostParser._getRichText_IG = function(text) {
      var exp;
      exp = /(\b(https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig;
      text = text.replace(exp, "<a href='$1' target='_blank'>$1</a>");
      exp = /@(\w+)/g;
      text = text.replace(exp, "<a href='http://www.instagram.com/$1' target='_blank'>@$1</a>");
      return text;
    };

    PostParser.getUsernameLink = function(post) {
      var nameLink, type;
      type = PostParser._getPostType(post);
      return nameLink = (function() {
        switch (true) {
          case type === 'twitter':
            return PostParser._getUsernameLink_TW(post);
          case type === 'instagram':
            return PostParser._getUsernameLink_IG(post);
        }
      })();
    };

    PostParser._getUsernameLink_TW = function(postData) {
      return "<a href=\"http://twitter.com/" + postData.user.screen_name + "\" target=\"_blank\">@" + postData.user.screen_name + "</a>";
    };

    PostParser._getUsernameLink_IG = function(postData) {
      return "<a href=\"http://instagram.com/" + postData.user.screen_name + "\" target=\"_blank\">@" + postData.user.screen_name + "</a>";
    };

    PostParser._getPostType = function(post) {
      if (/instagram/.test(post.source)) {
        return 'instagram';
      } else {
        return 'twitter';
      }
    };

    return PostParser;

  })();


  /*
   * Requester #
  
  Wrapper for `$.ajax` calls
   */

  Requester = (function() {
    function Requester() {}

    Requester.requests = [];

    Requester.request = function(data) {

      /*
      `data = {`<br>
      `  url         : String`<br>
      `  type        : "POST/GET/PUT"`<br>
      `  data        : Object`<br>
      `  dataType    : jQuery dataType`<br>
      `  contentType : String`<br>
      `}`
       */
      var r;
      r = $.ajax({
        url: data.url,
        type: data.type ? data.type : "POST",
        data: data.data ? data.data : null,
        dataType: data.dataType ? data.dataType : "json",
        contentType: data.contentType ? data.contentType : "application/x-www-form-urlencoded; charset=UTF-8",
        processData: data.processData !== null && data.processData !== void 0 ? data.processData : true
      });
      r.done(data.done);
      r.fail(data.fail);
      return r;
    };

    Requester.send = function(url, params) {

      /*
          POST shortcut
       */
      var formData, key, value, xhr;
      formData = new FormData;
      for (key in params) {
        value = params[key];
        formData.append(key, value);
      }
      xhr = new XMLHttpRequest;
      xhr.open("POST", url, true);
      xhr.onload = function(e) {
        return console.log(e);
      };
      xhr.send(formData);
      return null;
    };

    Requester.addImage = function(data, done, fail) {

      /*
      ** Usage: <br>
      `data = canvass.toDataURL("image/jpeg").slice("data:image/jpeg;base64,".length)`<br>
      `Requester.addImage data, "zoetrope", @done, @fail`
       */
      Requester.request({
        url: '/api/images/',
        type: 'POST',
        data: {
          image_base64: encodeURI(data)
        },
        done: done,
        fail: fail
      });
      return null;
    };

    Requester.deleteImage = function(id, done, fail) {
      Requester.request({
        url: '/api/images/' + id,
        type: 'DELETE',
        done: done,
        fail: fail
      });
      return null;
    };

    return Requester;

  })();


  /*
  Sharing class for non-SDK loaded social networks.
  If SDK is loaded, and provides share methods, then use that class instead, eg. `Facebook.share` instead of `Share.facebook`
   */

  Share = (function() {
    Share.prototype.url = null;

    function Share() {
      this.__NAMESPACE__ = __bind(this.__NAMESPACE__, this);
      this.weibo = __bind(this.weibo, this);
      this.renren = __bind(this.renren, this);
      this.twitter = __bind(this.twitter, this);
      this.facebook = __bind(this.facebook, this);
      this.tumblr = __bind(this.tumblr, this);
      this.pinterest = __bind(this.pinterest, this);
      this.plus = __bind(this.plus, this);
      this.openWin = __bind(this.openWin, this);
      this.url = this.__NAMESPACE__().BASE_PATH;
      return null;
    }

    Share.prototype.openWin = function(url, w, h) {
      var left, top;
      left = (screen.availWidth - w) >> 1;
      top = (screen.availHeight - h) >> 1;
      window.open(url, '', 'top=' + top + ',left=' + left + ',width=' + w + ',height=' + h + ',location=no,menubar=no');
      return null;
    };

    Share.prototype.plus = function(url) {
      url = encodeURIComponent(url || this.url);
      this.openWin("https://plus.google.com/share?url=" + url, 650, 385);
      return null;
    };

    Share.prototype.pinterest = function(url, media, descr) {
      url = encodeURIComponent(url || this.url);
      media = encodeURIComponent(media);
      descr = encodeURIComponent(descr);
      this.openWin("http://www.pinterest.com/pin/create/button/?url=" + url + "&media=" + media + "&description=" + descr, 735, 310);
      return null;
    };

    Share.prototype.tumblr = function(url, media, descr) {
      url = encodeURIComponent(url || this.url);
      media = encodeURIComponent(media);
      descr = encodeURIComponent(descr);
      this.openWin("http://www.tumblr.com/share/photo?source=" + media + "&caption=" + descr + "&click_thru=" + url, 450, 430);
      return null;
    };

    Share.prototype.facebook = function(url, copy) {
      var decsr;
      if (copy == null) {
        copy = '';
      }
      url = encodeURIComponent(url || this.url);
      decsr = encodeURIComponent(copy);
      this.openWin("http://www.facebook.com/share.php?u=" + url + "&t=" + decsr, 600, 300);
      return null;
    };

    Share.prototype.twitter = function(url, copy) {
      var descr;
      if (copy == null) {
        copy = '';
      }
      url = encodeURIComponent(url || this.url);
      if (copy === '') {
        copy = this.__NAMESPACE__().locale.get('seo_twitter_card_description');
      }
      descr = encodeURIComponent(copy);
      this.openWin("http://twitter.com/intent/tweet/?text=" + descr + "&url=" + url, 600, 300);
      return null;
    };

    Share.prototype.renren = function(url) {
      url = encodeURIComponent(url || this.url);
      this.openWin("http://share.renren.com/share/buttonshare.do?link=" + url, 600, 300);
      return null;
    };

    Share.prototype.weibo = function(url) {
      url = encodeURIComponent(url || this.url);
      this.openWin("http://service.weibo.com/share/share.php?url=" + url + "&language=zh_cn", 600, 300);
      return null;
    };

    Share.prototype.__NAMESPACE__ = function() {
      return view.__NAMESPACE__;
    };

    return Share;

  })();

  AbstractView = (function(_super) {
    __extends(AbstractView, _super);

    function AbstractView() {
      this.__NAMESPACE__ = __bind(this.__NAMESPACE__, this);
      this.dispose = __bind(this.dispose, this);
      this.callChildrenAndSelf = __bind(this.callChildrenAndSelf, this);
      this.callChildren = __bind(this.callChildren, this);
      this.triggerChildren = __bind(this.triggerChildren, this);
      this.removeAllChildren = __bind(this.removeAllChildren, this);
      this.muteAll = __bind(this.muteAll, this);
      this.unMuteAll = __bind(this.unMuteAll, this);
      this.CSSTranslate = __bind(this.CSSTranslate, this);
      this.mouseEnabled = __bind(this.mouseEnabled, this);
      this.onResize = __bind(this.onResize, this);
      this.remove = __bind(this.remove, this);
      this.replace = __bind(this.replace, this);
      this.addChild = __bind(this.addChild, this);
      this.render = __bind(this.render, this);
      this.update = __bind(this.update, this);
      this.init = __bind(this.init, this);
      return AbstractView.__super__.constructor.apply(this, arguments);
    }

    AbstractView.prototype.el = null;

    AbstractView.prototype.id = null;

    AbstractView.prototype.children = null;

    AbstractView.prototype.template = null;

    AbstractView.prototype.templateVars = null;

    AbstractView.prototype.initialize = function() {
      var tmpHTML;
      this.children = [];
      if (this.template) {
        tmpHTML = _.template(this.__NAMESPACE__().templates.get(this.template));
        this.setElement(tmpHTML(this.templateVars));
      }
      if (this.id) {
        this.$el.attr('id', this.id);
      }
      if (this.className) {
        this.$el.addClass(this.className);
      }
      this.init();
      this.paused = false;
      return null;
    };

    AbstractView.prototype.init = function() {
      return null;
    };

    AbstractView.prototype.update = function() {
      return null;
    };

    AbstractView.prototype.render = function() {
      return null;
    };

    AbstractView.prototype.addChild = function(child, prepend) {
      var c, target;
      if (prepend == null) {
        prepend = false;
      }
      if (child.el) {
        this.children.push(child);
      }
      target = this.addToSelector ? this.$el.find(this.addToSelector).eq(0) : this.$el;
      c = child.el ? child.$el : child;
      if (!prepend) {
        target.append(c);
      } else {
        target.prepend(c);
      }
      return this;
    };

    AbstractView.prototype.replace = function(dom, child) {
      var c;
      if (child.el) {
        this.children.push(child);
      }
      c = child.el ? child.$el : child;
      this.$el.children(dom).replaceWith(c);
      return null;
    };

    AbstractView.prototype.remove = function(child) {
      var c;
      if (child == null) {
        return;
      }
      c = child.el ? child.$el : $(child);
      if (c && child.dispose) {
        child.dispose();
      }
      if (c && this.children.indexOf(child) !== -1) {
        this.children.splice(this.children.indexOf(child), 1);
      }
      c.remove();
      return null;
    };

    AbstractView.prototype.onResize = function(event) {
      var child, _i, _len, _ref;
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (child.onResize) {
          child.onResize();
        }
      }
      return null;
    };

    AbstractView.prototype.mouseEnabled = function(enabled) {
      this.$el.css({
        "pointer-events": enabled ? "auto" : "none"
      });
      return null;
    };

    AbstractView.prototype.CSSTranslate = function(x, y, value, scale) {
      var str;
      if (value == null) {
        value = '%';
      }
      if (Modernizr.csstransforms3d) {
        str = "translate3d(" + (x + value) + ", " + (y + value) + ", 0)";
      } else {
        str = "translate(" + (x + value) + ", " + (y + value) + ")";
      }
      if (scale) {
        str = "" + str + " scale(" + scale + ")";
      }
      return str;
    };

    AbstractView.prototype.unMuteAll = function() {
      var child, _i, _len, _ref;
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (typeof child.unMute === "function") {
          child.unMute();
        }
        if (child.children.length) {
          child.unMuteAll();
        }
      }
      return null;
    };

    AbstractView.prototype.muteAll = function() {
      var child, _i, _len, _ref;
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        if (typeof child.mute === "function") {
          child.mute();
        }
        if (child.children.length) {
          child.muteAll();
        }
      }
      return null;
    };

    AbstractView.prototype.removeAllChildren = function() {
      var child, _i, _len, _ref;
      _ref = this.children;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        child = _ref[_i];
        this.remove(child);
      }
      return null;
    };

    AbstractView.prototype.triggerChildren = function(msg, children) {
      var child, i, _i, _len;
      if (children == null) {
        children = this.children;
      }
      for (i = _i = 0, _len = children.length; _i < _len; i = ++_i) {
        child = children[i];
        child.trigger(msg);
        if (child.children.length) {
          this.triggerChildren(msg, child.children);
        }
      }
      return null;
    };

    AbstractView.prototype.callChildren = function(method, params, children) {
      var child, i, _i, _len;
      if (children == null) {
        children = this.children;
      }
      for (i = _i = 0, _len = children.length; _i < _len; i = ++_i) {
        child = children[i];
        if (typeof child[method] === "function") {
          child[method](params);
        }
        if (child.children.length) {
          this.callChildren(method, params, child.children);
        }
      }
      return null;
    };

    AbstractView.prototype.callChildrenAndSelf = function(method, params, children) {
      var child, i, _i, _len;
      if (children == null) {
        children = this.children;
      }
      if (typeof this[method] === "function") {
        this[method](params);
      }
      for (i = _i = 0, _len = children.length; _i < _len; i = ++_i) {
        child = children[i];
        if (typeof child[method] === "function") {
          child[method](params);
        }
        if (child.children.length) {
          this.callChildren(method, params, child.children);
        }
      }
      return null;
    };

    AbstractView.prototype.supplantString = function(str, vals) {
      return str.replace(/{{ ([^{}]*) }}/g, function(a, b) {
        var r;
        r = vals[b];
        if (typeof r === "string" || typeof r === "number") {
          return r;
        } else {
          return a;
        }
      });
    };

    AbstractView.prototype.dispose = function() {

      /*
      		override on per view basis - unbind event handlers etc
       */
      return null;
    };

    AbstractView.prototype.__NAMESPACE__ = function() {
      return view.__NAMESPACE__;
    };

    return AbstractView;

  })(Backbone.View);

  AbstractViewModal = (function(_super) {
    __extends(AbstractViewModal, _super);

    function AbstractViewModal() {
      this.animateOutDone = __bind(this.animateOutDone, this);
      this.animateOut = __bind(this.animateOut, this);
      this.animateInDone = __bind(this.animateInDone, this);
      this.animateIn = __bind(this.animateIn, this);
      this.close = __bind(this.close, this);
      this.onCloseClick = __bind(this.onCloseClick, this);
      this.setListeners = __bind(this.setListeners, this);
      this.dispose = __bind(this.dispose, this);
      this.hide = __bind(this.hide, this);
      this.show = __bind(this.show, this);
      return AbstractViewModal.__super__.constructor.apply(this, arguments);
    }

    AbstractViewModal.prototype._shown = false;

    AbstractViewModal.prototype._listening = false;

    AbstractViewModal.prototype.TRANSITION_TIME = 0.3;

    AbstractViewModal.prototype.show = function(cb) {
      if (!!this._shown) {
        return;
      }
      this._shown = true;
      this.brz().appView.wrapper.addChild(this);
      this.animateIn(cb);
      return null;
    };

    AbstractViewModal.prototype.hide = function(cb) {
      if (!this._shown) {
        return;
      }
      this._shown = false;
      this.animateOut(cb);
      return null;
    };

    AbstractViewModal.prototype.dispose = function() {
      this.callChildrenAndSelf('setListeners', 'off');
      return null;
    };

    AbstractViewModal.prototype.setListeners = function(setting) {
      if (setting === this._listening) {
        return 'noListenerChange';
      }
      this._listening = setting;
      this.$el[setting]('click', '[data-close-modal]', this.onCloseClick);
      return null;
    };

    AbstractViewModal.prototype.onCloseClick = function(e) {
      e.preventDefault();
      this.close();
      return null;
    };

    AbstractViewModal.prototype.close = function() {
      this.brz().router.navigateTo(this.brz().appView.wrapper.backgroundView.route);
      return null;
    };

    AbstractViewModal.prototype.animateIn = function(cb) {
      this.$el.css({
        'visibility': 'visible'
      });
      TweenLite.fromTo(this.$el, this.TRANSITION_TIME, {
        'transform': this.CSSTranslate(-50, -45),
        'opacity': 0
      }, {
        'transform': this.CSSTranslate(-50, -50),
        'opacity': 1,
        ease: Cubic.easeInOut,
        onComplete: this.animateInDone,
        onCompleteParams: [cb]
      });
      return null;
    };

    AbstractViewModal.prototype.animateInDone = function(cb) {
      this.callChildrenAndSelf('setListeners', 'on');
      if (typeof cb === "function") {
        cb();
      }
      this.brz().appView.modalPlayBtn.show();
      return null;
    };

    AbstractViewModal.prototype.animateOut = function(cb) {
      this.brz().appView.modalPlayBtn.hide();
      TweenLite.to(this.$el, this.TRANSITION_TIME, {
        'transform': this.CSSTranslate(-50, -55),
        'opacity': 0,
        ease: Cubic.easeInOut,
        onComplete: this.animateOutDone,
        onCompleteParams: [cb]
      });
      return null;
    };

    AbstractViewModal.prototype.animateOutDone = function(cb) {
      this.$el.css({
        'visibility': 'hidden'
      });
      this.brz().appView.wrapper.remove(this);
      if (typeof cb === "function") {
        cb();
      }
      return null;
    };

    return AbstractViewModal;

  })(AbstractView);

  AbstractViewPage = (function(_super) {
    __extends(AbstractViewPage, _super);

    function AbstractViewPage() {
      this.setListeners = __bind(this.setListeners, this);
      this.hide = __bind(this.hide, this);
      this.show = __bind(this.show, this);
      return AbstractViewPage.__super__.constructor.apply(this, arguments);
    }

    AbstractViewPage.prototype._shown = false;

    AbstractViewPage.prototype._listening = false;

    AbstractViewPage.prototype.show = function(cb) {
      if (!!this._shown) {
        return;
      }
      this._shown = true;

      /*
      		CHANGE HERE - 'page' views are always in DOM - to save having to re-initialise gmap events (PITA). No longer require :dispose method
       */
      this.callChildrenAndSelf('setListeners', 'on');

      /* replace with some proper transition if we can */
      this.$el.css({
        'visibility': 'visible'
      });
      if (typeof cb === "function") {
        cb();
      }
      return null;
    };

    AbstractViewPage.prototype.hide = function(cb) {
      if (!this._shown) {
        return;
      }
      this._shown = false;

      /*
      		CHANGE HERE - 'page' views are always in DOM - to save having to re-initialise gmap events (PITA). No longer require :dispose method
       */
      this.callChildrenAndSelf('setListeners', 'off');

      /* replace with some proper transition if we can */
      this.$el.css({
        'visibility': 'hidden'
      });
      if (typeof cb === "function") {
        cb();
      }
      return null;
    };

    AbstractViewPage.prototype.setListeners = function(setting) {
      if (setting === this._listening) {
        return;
      }
      this._listening = setting;
      return null;
    };

    return AbstractViewPage;

  })(AbstractView);

  Footer = (function(_super) {
    __extends(Footer, _super);

    Footer.prototype.template = 'site-footer';

    function Footer() {
      this.templateVars = {
        desc: this.__NAMESPACE__().locale.get("footer_desc")
      };
      Footer.__super__.constructor.call(this);
      return null;
    }

    return Footer;

  })(AbstractView);

  Header = (function(_super) {
    __extends(Header, _super);

    Header.prototype.template = 'site-header';

    function Header() {
      this.templateVars = {
        desc: this.__NAMESPACE__().locale.get("header_desc"),
        home: {
          label: 'Go to homepage',
          url: this.__NAMESPACE__().BASE_PATH + '/' + this.__NAMESPACE__().nav.sections.HOME
        },
        example: {
          label: 'Go to example page',
          url: this.__NAMESPACE__().BASE_PATH + '/' + this.__NAMESPACE__().nav.sections.EXAMPLE
        }
      };
      Header.__super__.constructor.call(this);
      return null;
    }

    return Header;

  })(AbstractView);

  Preloader = (function(_super) {
    __extends(Preloader, _super);

    Preloader.prototype.cb = null;

    Preloader.prototype.TRANSITION_TIME = 0.5;

    function Preloader() {
      this.onHideComplete = __bind(this.onHideComplete, this);
      this.hide = __bind(this.hide, this);
      this.onShowComplete = __bind(this.onShowComplete, this);
      this.show = __bind(this.show, this);
      this.init = __bind(this.init, this);
      this.setElement($('#preloader'));
      Preloader.__super__.constructor.call(this);
      return null;
    }

    Preloader.prototype.init = function() {
      return null;
    };

    Preloader.prototype.show = function(cb) {
      this.cb = cb;
      this.$el.css({
        'display': 'block'
      });
      return null;
    };

    Preloader.prototype.onShowComplete = function() {
      if (typeof this.cb === "function") {
        this.cb();
      }
      return null;
    };

    Preloader.prototype.hide = function(cb) {
      this.cb = cb;
      this.onHideComplete();
      return null;
    };

    Preloader.prototype.onHideComplete = function() {
      this.$el.css({
        'display': 'none'
      });
      if (typeof this.cb === "function") {
        this.cb();
      }
      return null;
    };

    return Preloader;

  })(AbstractView);

  Wrapper = (function(_super) {
    __extends(Wrapper, _super);

    Wrapper.prototype.VIEW_TYPE_PAGE = 'page';

    Wrapper.prototype.VIEW_TYPE_MODAL = 'modal';

    Wrapper.prototype.template = 'wrapper';

    Wrapper.prototype.views = null;

    Wrapper.prototype.previousView = null;

    Wrapper.prototype.currentView = null;

    Wrapper.prototype.backgroundView = null;

    function Wrapper() {
      this.transitionViews = __bind(this.transitionViews, this);
      this.changeSubView = __bind(this.changeSubView, this);
      this.changeView = __bind(this.changeView, this);
      this.bindEvents = __bind(this.bindEvents, this);
      this.start = __bind(this.start, this);
      this.init = __bind(this.init, this);
      this.getViewByRoute = __bind(this.getViewByRoute, this);
      this.addClasses = __bind(this.addClasses, this);
      this.createClasses = __bind(this.createClasses, this);
      this.views = {
        home: {
          classRef: HomeView,
          route: this.__NAMESPACE__().nav.sections.HOME,
          view: null,
          type: this.VIEW_TYPE_PAGE
        },
        quests: {
          classRef: ExamplePageView,
          route: this.__NAMESPACE__().nav.sections.EXAMPLE,
          view: null,
          type: this.VIEW_TYPE_PAGE
        }
      };
      this.createClasses();
      Wrapper.__super__.constructor.call(this);
      this.addClasses();
      return null;
    }

    Wrapper.prototype.createClasses = function() {
      var data, name, _ref;
      _ref = this.views;
      for (name in _ref) {
        data = _ref[name];
        this.views[name].view = new this.views[name].classRef;
      }
      return null;
    };

    Wrapper.prototype.addClasses = function() {
      var data, name, _ref, _results;
      _ref = this.views;
      _results = [];
      for (name in _ref) {
        data = _ref[name];
        if (data.type === this.VIEW_TYPE_PAGE) {
          _results.push(this.addChild(data.view));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    null;

    Wrapper.prototype.getViewByRoute = function(route) {
      var data, name, _ref;
      _ref = this.views;
      for (name in _ref) {
        data = _ref[name];
        if (route === this.views[name].route) {
          return this.views[name];
        }
      }
      return null;
    };

    Wrapper.prototype.init = function() {
      this.__NAMESPACE__().appView.on('start', this.start);
      return null;
    };

    Wrapper.prototype.start = function() {
      this.__NAMESPACE__().appView.off('start', this.start);
      this.bindEvents();
      return null;
    };

    Wrapper.prototype.bindEvents = function() {
      this.__NAMESPACE__().nav.on(Nav.EVENT_CHANGE_VIEW, this.changeView);
      this.__NAMESPACE__().nav.on(Nav.EVENT_CHANGE_SUB_VIEW, this.changeSubView);
      return null;
    };


    /*
    
    	THIS IS A MESS, SORT IT (neil)
     */

    Wrapper.prototype.changeView = function(previous, current) {
      this.previousView = this.getViewByRoute(previous.area);
      this.currentView = this.getViewByRoute(current.area);
      if (!this.previousView) {
        if (this.currentView.type === this.VIEW_TYPE_PAGE) {
          this.transitionViews(false, this.currentView.view);
        } else if (this.currentView.type === this.VIEW_TYPE_MODAL) {
          this.backgroundView = this.views.home;
          this.transitionViews(false, this.currentView.view, true);
        }
      } else {
        if (this.currentView.type === this.VIEW_TYPE_PAGE && this.previousView.type === this.VIEW_TYPE_PAGE) {
          this.transitionViews(this.previousView.view, this.currentView.view);
        } else if (this.currentView.type === this.VIEW_TYPE_MODAL && this.previousView.type === this.VIEW_TYPE_PAGE) {
          this.backgroundView = this.previousView;
          this.transitionViews(false, this.currentView.view, true);
        } else if (this.currentView.type === this.VIEW_TYPE_PAGE && this.previousView.type === this.VIEW_TYPE_MODAL) {
          this.backgroundView = this.backgroundView || this.views.home;
          if (this.backgroundView !== this.currentView) {
            this.transitionViews(this.previousView.view, this.currentView.view, false, true);
          } else if (this.backgroundView === this.currentView) {
            this.transitionViews(this.previousView.view, false);
          }
        } else if (this.currentView.type === this.VIEW_TYPE_MODAL && this.previousView.type === this.VIEW_TYPE_MODAL) {
          this.backgroundView = this.backgroundView || this.views.home;
          this.transitionViews(this.previousView.view, this.currentView.view, true);
        }
      }
      return null;
    };

    Wrapper.prototype.changeSubView = function(current) {
      this.currentView.view.trigger(Nav.EVENT_CHANGE_SUB_VIEW, current.sub);
      return null;
    };

    Wrapper.prototype.transitionViews = function(from, to, toModal, fromModal) {
      var _ref, _ref1;
      if (toModal == null) {
        toModal = false;
      }
      if (fromModal == null) {
        fromModal = false;
      }
      if (from === to) {
        return;
      }
      if (toModal) {
        if ((_ref = this.backgroundView.view) != null) {
          _ref.show();
        }
      }
      if (fromModal) {
        if ((_ref1 = this.backgroundView.view) != null) {
          _ref1.hide();
        }
      }
      if (from && to) {
        from.hide(to.show);
      } else if (from) {
        from.hide();
      } else if (to) {
        to.show();
      }
      return null;
    };

    return Wrapper;

  })(AbstractView);

  ExamplePageView = (function(_super) {
    __extends(ExamplePageView, _super);

    ExamplePageView.prototype.template = 'page-example';

    function ExamplePageView() {
      this.templateVars = {
        desc: this.__NAMESPACE__().locale.get("example_desc")
      };

      /*
      
      		instantiate classes here
      
      		@exampleClass = new ExampleClass
       */
      ExamplePageView.__super__.constructor.call(this);

      /*
      
      		add classes to app structure here
      
      		@
      			.addChild(@exampleClass)
       */
      return null;
    }

    return ExamplePageView;

  })(AbstractViewPage);

  HomeView = (function(_super) {
    __extends(HomeView, _super);

    HomeView.prototype.template = 'page-home';

    function HomeView() {
      this.templateVars = {
        desc: this.__NAMESPACE__().locale.get("home_desc")
      };

      /*
      
      		instantiate classes here
      
      		@exampleClass = new ExampleClass
       */
      HomeView.__super__.constructor.call(this);

      /*
      
      		add classes to app structure here
      
      		@
      			.addChild(@exampleClass)
       */
      return null;
    }

    return HomeView;

  })(AbstractViewPage);

  AbstractModal = (function(_super) {
    __extends(AbstractModal, _super);

    AbstractModal.prototype.$window = null;


    /* override in individual classes */

    AbstractModal.prototype.name = null;

    AbstractModal.prototype.template = null;

    function AbstractModal() {
      this.closeClick = __bind(this.closeClick, this);
      this.animateOut = __bind(this.animateOut, this);
      this.animateIn = __bind(this.animateIn, this);
      this.onKeyUp = __bind(this.onKeyUp, this);
      this.setListeners = __bind(this.setListeners, this);
      this.dispose = __bind(this.dispose, this);
      this.hide = __bind(this.hide, this);
      this.$window = $(window);
      AbstractModal.__super__.constructor.call(this);
      this.__NAMESPACE__().appView.addChild(this);
      this.setListeners('on');
      this.animateIn();
      return null;
    }

    AbstractModal.prototype.hide = function() {
      this.animateOut((function(_this) {
        return function() {
          return _this.__NAMESPACE__().appView.remove(_this);
        };
      })(this));
      return null;
    };

    AbstractModal.prototype.dispose = function() {
      this.setListeners('off');
      this.__NAMESPACE__().appView.modalManager.modals[this.name].view = null;
      return null;
    };

    AbstractModal.prototype.setListeners = function(setting) {
      this.$window[setting]('keyup', this.onKeyUp);
      this.$('[data-close]')[setting]('click', this.closeClick);
      return null;
    };

    AbstractModal.prototype.onKeyUp = function(e) {
      if (e.keyCode === 27) {
        this.hide();
      }
      return null;
    };

    AbstractModal.prototype.animateIn = function() {
      TweenLite.to(this.$el, 0.3, {
        'visibility': 'visible',
        'opacity': 1,
        ease: Quad.easeOut
      });
      TweenLite.to(this.$el.find('.inner'), 0.3, {
        delay: 0.15,
        'transform': 'scale(1)',
        'visibility': 'visible',
        'opacity': 1,
        ease: Back.easeOut
      });
      return null;
    };

    AbstractModal.prototype.animateOut = function(callback) {
      TweenLite.to(this.$el, 0.3, {
        delay: 0.15,
        'opacity': 0,
        ease: Quad.easeOut,
        onComplete: callback
      });
      TweenLite.to(this.$el.find('.inner'), 0.3, {
        'transform': 'scale(0.8)',
        'opacity': 0,
        ease: Back.easeIn
      });
      return null;
    };

    AbstractModal.prototype.closeClick = function(e) {
      e.preventDefault();
      this.hide();
      return null;
    };

    return AbstractModal;

  })(AbstractView);

  OrientationModal = (function(_super) {
    __extends(OrientationModal, _super);

    OrientationModal.prototype.name = 'orientationModal';

    OrientationModal.prototype.template = 'orientation-modal';

    OrientationModal.prototype.cb = null;

    function OrientationModal(cb) {
      this.cb = cb;
      this.onUpdateDims = __bind(this.onUpdateDims, this);
      this.setListeners = __bind(this.setListeners, this);
      this.hide = __bind(this.hide, this);
      this.init = __bind(this.init, this);
      this.templateVars = {
        name: this.name
      };
      OrientationModal.__super__.constructor.call(this);
      return null;
    }

    OrientationModal.prototype.init = function() {
      return null;
    };

    OrientationModal.prototype.hide = function(stillLandscape) {
      if (stillLandscape == null) {
        stillLandscape = true;
      }
      this.animateOut((function(_this) {
        return function() {
          _this.__NAMESPACE__().appView.remove(_this);
          if (!stillLandscape) {
            return typeof _this.cb === "function" ? _this.cb() : void 0;
          }
        };
      })(this));
      return null;
    };

    OrientationModal.prototype.setListeners = function(setting) {
      OrientationModal.__super__.setListeners.apply(this, arguments);
      this.__NAMESPACE__().appView[setting]('updateDims', this.onUpdateDims);
      this.$el[setting]('touchend click', this.hide);
      return null;
    };

    OrientationModal.prototype.onUpdateDims = function(dims) {
      if (dims.o === 'portrait') {
        this.hide(false);
      }
      return null;
    };

    return OrientationModal;

  })(AbstractModal);

  ModalManager = (function(_super) {
    __extends(ModalManager, _super);

    ModalManager.prototype.modals = {
      orientationModal: {
        classRef: OrientationModal,
        view: null
      }
    };

    function ModalManager() {
      this.showModal = __bind(this.showModal, this);
      this.hideOpenModal = __bind(this.hideOpenModal, this);
      this.isOpen = __bind(this.isOpen, this);
      this.init = __bind(this.init, this);
      ModalManager.__super__.constructor.call(this);
      return null;
    }

    ModalManager.prototype.init = function() {
      return null;
    };

    ModalManager.prototype.isOpen = function() {
      var modal, name, _ref;
      _ref = this.modals;
      for (name in _ref) {
        modal = _ref[name];
        if (this.modals[name].view) {
          return true;
        }
      }
      return false;
    };

    ModalManager.prototype.hideOpenModal = function() {
      var modal, name, openModal, _ref;
      _ref = this.modals;
      for (name in _ref) {
        modal = _ref[name];
        if (this.modals[name].view) {
          openModal = this.modals[name].view;
        }
      }
      if (openModal != null) {
        openModal.hide();
      }
      return null;
    };

    ModalManager.prototype.showModal = function(name, cb) {
      if (cb == null) {
        cb = null;
      }
      if (this.modals[name].view) {
        return;
      }
      this.modals[name].view = new this.modals[name].classRef(cb);
      return null;
    };

    return ModalManager;

  })(AbstractView);

  Nav = (function(_super) {
    __extends(Nav, _super);

    Nav.EVENT_CHANGE_VIEW = 'EVENT_CHANGE_VIEW';

    Nav.EVENT_CHANGE_SUB_VIEW = 'EVENT_CHANGE_SUB_VIEW';

    Nav.prototype.sections = {
      HOME: '',
      EXAMPLE: 'example'
    };

    Nav.prototype.current = {
      area: null,
      sub: null
    };

    Nav.prototype.previous = {
      area: null,
      sub: null
    };

    function Nav() {
      this.setPageTitle = __bind(this.setPageTitle, this);
      this.changeView = __bind(this.changeView, this);
      this.getSection = __bind(this.getSection, this);
      this.__NAMESPACE__().router.on(Router.EVENT_HASH_CHANGED, this.changeView);
      return false;
    }

    Nav.prototype.getSection = function(section) {
      var sectionName, uri, _ref;
      if (section === '') {
        return true;
      }
      _ref = this.sections;
      for (sectionName in _ref) {
        uri = _ref[sectionName];
        if (uri === section) {
          return sectionName;
        }
      }
      return false;
    };

    Nav.prototype.changeView = function(area, sub, params) {
      this.previous = this.current;
      this.current = {
        area: area,
        sub: sub
      };
      if (this.previous.area && this.previous.area === this.current.area) {
        this.trigger(Nav.EVENT_CHANGE_SUB_VIEW, this.current);
      } else {
        this.trigger(Nav.EVENT_CHANGE_VIEW, this.previous, this.current);
        this.trigger(Nav.EVENT_CHANGE_SUB_VIEW, this.current);
      }
      if (this.__NAMESPACE__().appView.modalManager.isOpen()) {
        this.__NAMESPACE__().appView.modalManager.hideOpenModal();
      }
      this.setPageTitle(area, sub);
      return null;
    };

    Nav.prototype.setPageTitle = function(area, sub) {
      var title;
      title = "PAGE TITLE HERE - LOCALISE BASED ON URL";
      if (window.document.title !== title) {
        window.document.title = title;
      }
      return null;
    };

    return Nav;

  })(AbstractView);

  Router = (function(_super) {
    __extends(Router, _super);

    function Router() {
      this.__NAMESPACE__ = __bind(this.__NAMESPACE__, this);
      this.navigateTo = __bind(this.navigateTo, this);
      this.hashChanged = __bind(this.hashChanged, this);
      this.start = __bind(this.start, this);
      return Router.__super__.constructor.apply(this, arguments);
    }

    Router.EVENT_HASH_CHANGED = 'EVENT_HASH_CHANGED';

    Router.prototype.FIRST_ROUTE = true;

    Router.prototype.routes = {
      '(/)(:area)(/:sub)(/)': 'hashChanged',
      '*actions': 'navigateTo'
    };

    Router.prototype.area = null;

    Router.prototype.sub = null;

    Router.prototype.params = null;

    Router.prototype.start = function() {
      Backbone.history.start({
        pushState: true,
        root: '/'
      });
      return null;
    };

    Router.prototype.hashChanged = function(area, sub) {
      this.area = area != null ? area : null;
      this.sub = sub != null ? sub : null;
      console.log(">> EVENT_HASH_CHANGED @area = " + this.area + ", @sub = " + this.sub + " <<");
      if (this.FIRST_ROUTE) {
        this.FIRST_ROUTE = false;
      }
      if (!this.area) {
        this.area = this.__NAMESPACE__().nav.sections.HOME;
      }
      this.trigger(Router.EVENT_HASH_CHANGED, this.area, this.sub, this.params);
      return null;
    };

    Router.prototype.navigateTo = function(where, trigger, replace, params) {
      if (where == null) {
        where = '';
      }
      if (trigger == null) {
        trigger = true;
      }
      if (replace == null) {
        replace = false;
      }
      this.params = params;
      if (where.charAt(0) !== "/") {
        where = "/" + where;
      }
      if (where.charAt(where.length - 1) !== "/") {
        where = "" + where + "/";
      }
      if (!trigger) {
        this.trigger(Router.EVENT_HASH_CHANGED, where, null, this.params);
        return;
      }
      this.navigate(where, {
        trigger: true,
        replace: replace
      });
      return null;
    };

    Router.prototype.__NAMESPACE__ = function() {
      return view.__NAMESPACE__;
    };

    return Router;

  })(Backbone.Router);

  AppView = (function(_super) {
    __extends(AppView, _super);

    AppView.prototype.template = 'main';

    AppView.prototype.$window = null;

    AppView.prototype.$body = null;

    AppView.prototype.wrapper = null;

    AppView.prototype.footer = null;

    AppView.prototype.dims = {
      w: null,
      h: null,
      o: null,
      c: null
    };

    AppView.prototype.events = {
      'click a': 'linkManager'
    };

    AppView.prototype.EVENT_UPDATE_DIMENSIONS = 'EVENT_UPDATE_DIMENSIONS';

    AppView.prototype.MOBILE_WIDTH = 700;

    AppView.prototype.MOBILE = 'mobile';

    AppView.prototype.NON_MOBILE = 'non_mobile';

    function AppView() {
      this.handleExternalLink = __bind(this.handleExternalLink, this);
      this.navigateToUrl = __bind(this.navigateToUrl, this);
      this.linkManager = __bind(this.linkManager, this);
      this.getDims = __bind(this.getDims, this);
      this.onResize = __bind(this.onResize, this);
      this.begin = __bind(this.begin, this);
      this.onAllRendered = __bind(this.onAllRendered, this);
      this.bindEvents = __bind(this.bindEvents, this);
      this.render = __bind(this.render, this);
      this.enableTouch = __bind(this.enableTouch, this);
      this.disableTouch = __bind(this.disableTouch, this);
      this.$window = $(window);
      this.$body = $('body').eq(0);
      AppView.__super__.constructor.call(this);
      return null;
    }

    AppView.prototype.disableTouch = function() {
      this.$window.on('touchmove', this.onTouchMove);
      return null;
    };

    AppView.prototype.enableTouch = function() {
      this.$window.off('touchmove', this.onTouchMove);
      return null;
    };

    AppView.prototype.onTouchMove = function(e) {
      e.preventDefault();
      return null;
    };

    AppView.prototype.render = function() {
      this.bindEvents();
      this.preloader = new Preloader;
      this.modalManager = new ModalManager;
      this.header = new Header;
      this.wrapper = new Wrapper;
      this.footer = new Footer;
      this.addChild(this.header).addChild(this.wrapper).addChild(this.footer);
      this.onAllRendered();
      return null;
    };

    AppView.prototype.bindEvents = function() {
      this.on('allRendered', this.onAllRendered);
      this.onResize();
      this.onResize = _.debounce(this.onResize, 300);
      this.$window.on('resize orientationchange', this.onResize);
      return null;
    };

    AppView.prototype.onAllRendered = function() {
      this.$body.prepend(this.$el);
      this.begin();
      return null;
    };

    AppView.prototype.begin = function() {
      this.trigger('start');
      this.__NAMESPACE__().router.start();
      this.preloader.hide();
      return null;
    };

    AppView.prototype.onResize = function() {
      this.getDims();
      return null;
    };

    AppView.prototype.getDims = function() {
      var h, w;
      w = window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth;
      h = window.innerHeight || document.documentElement.clientHeight || document.body.clientHeight;
      this.dims = {
        w: w,
        h: h,
        o: h > w ? 'portrait' : 'landscape',
        c: w <= this.MOBILE_WIDTH ? this.MOBILE : this.NON_MOBILE
      };
      this.trigger(this.EVENT_UPDATE_DIMENSIONS, this.dims);
      return null;
    };

    AppView.prototype.linkManager = function(e) {
      var href;
      href = $(e.currentTarget).attr('href');
      if (!href) {
        return false;
      }
      this.navigateToUrl(href, e);
      return null;
    };

    AppView.prototype.navigateToUrl = function(href, e) {
      var route, section;
      if (e == null) {
        e = null;
      }
      route = href.match(this.__NAMESPACE__().BASE_PATH) ? href.split(this.__NAMESPACE__().BASE_PATH)[1] : href;
      section = route.indexOf('/') === 0 ? route.split('/')[1] : route;
      if (this.__NAMESPACE__().nav.getSection(section)) {
        if (e != null) {
          e.preventDefault();
        }
        this.__NAMESPACE__().router.navigateTo(route);
      } else {
        this.handleExternalLink(href);
      }
      return null;
    };

    AppView.prototype.handleExternalLink = function(data) {

      /*
      
      		bind tracking events if necessary
       */
      return null;
    };

    return AppView;

  })(AbstractView);

  App = (function() {
    App.prototype.LIVE = null;

    App.prototype.BASE_PATH = window.config.hostname;

    App.prototype.localeCode = window.config.localeCode;

    App.prototype.objReady = 0;

    App.prototype._toClean = ['objReady', 'setFlags', 'objectComplete', 'init', 'initObjects', 'initSDKs', 'initApp', 'go', 'cleanup', '_toClean'];

    function App(LIVE) {
      this.LIVE = LIVE;
      this.cleanup = __bind(this.cleanup, this);
      this.go = __bind(this.go, this);
      this.initApp = __bind(this.initApp, this);
      this.initSDKs = __bind(this.initSDKs, this);
      this.initObjects = __bind(this.initObjects, this);
      this.init = __bind(this.init, this);
      this.objectComplete = __bind(this.objectComplete, this);
      this.setFlags = __bind(this.setFlags, this);
      return null;
    }

    App.prototype.setFlags = function() {
      var ua;
      ua = navigator.userAgent.toLowerCase();
      this.IS_ANDROID = ua.indexOf('android') > -1;
      this.IS_FIREFOX = ua.indexOf('firefox') > -1;
      this.IS_CHROME_IOS = ua.match('crios') ? true : false;
      return null;
    };

    App.prototype.objectComplete = function() {
      this.objReady++;
      if (this.objReady >= 4) {
        this.initApp();
      }
      return null;
    };

    App.prototype.init = function() {
      this.initObjects();
      return null;
    };

    App.prototype.initObjects = function() {
      this.templates = new Templates("/data/templates" + (this.LIVE ? '.min' : '') + ".xml", this.objectComplete);
      this.locale = new Locale("/data/locales/strings.json", this.objectComplete);
      this.analytics = new Analytics("/data/tracking.json", this.objectComplete);
      this.appData = new AppData(this.objectComplete);
      return null;
    };

    App.prototype.initSDKs = function() {
      Facebook.load();
      GooglePlus.load();
      return null;
    };

    App.prototype.initApp = function() {
      this.setFlags();

      /* Starts application */
      this.appView = new AppView;
      this.router = new Router;
      this.nav = new Nav;
      this.auth = new AuthManager;
      this.share = new Share;
      this.go();
      this.initSDKs();
      return null;
    };

    App.prototype.go = function() {

      /* After everything is loaded, kicks off website */
      this.appView.render();

      /* remove redundant initialisation methods / properties */
      this.cleanup();
      return null;
    };

    App.prototype.cleanup = function() {
      var fn, _i, _len, _ref;
      _ref = this._toClean;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        fn = _ref[_i];
        this[fn] = null;
        delete this[fn];
      }
      return null;
    };

    return App;

  })();

  IS_LIVE = (function() {
    if (window.location.host.indexOf('localhost') > -1 || window.location.search === '?d') {
      return false;
    } else {
      return true;
    }
  })();

  view = IS_LIVE ? {} : window || document;

  view.__NAMESPACE__ = new App(IS_LIVE);

  view.__NAMESPACE__.init();

}).call(this);
